daos:
  # - code: degov-with-blocknumber
  #   xprofile: official
  #   carry:
  #     - "#Governance"
  #     - "#DeFAI"
  #     - "#DAO"
  #   extend: http://degovtrial-webdemowithblocknumber-jpt8mz-911581-168-119-79-153.traefik.me/degov.yml

  - name: DeGov Development Test DAO
    code: degov-demo-dao
    # xprofile: roasted
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://demo.degov.ai
      config: https://demo.degov.ai/degov.yml
      indexer: https://degov-indexer.vercel.app/graphql

  - name: RingDAO
    code: ring-dao
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://gov.ringdao.com
      config: https://gov.ringdao.com/degov.yml
      indexer: https://gov.ringdao.com/indexer/graphql

  - name: KtonDAO
    code: kton-dao
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://gov.ktondao.xyz
      config: https://gov.ktondao.xyz/degov.yml
      indexer: https://gov.ktondao.xyz/indexer/graphql

  - name: RingDAO Community Guild
    code: ringdao-guild
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://guild-gov.ringdao.com
      config: https://guild-gov.ringdao.com/degov.yml
      indexer: https://guild-gov.ringdao.com/indexer/graphql

  - name: ENS DAO
    code: ens-dao
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://ens.degov.ai
      config: https://ens.degov.ai/degov.yml
      indexer: https://ens.degov.ai/indexer/graphql

  - name: Aquari DAO
    code: aquari-dao
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://aquari.degov.ai
      config: https://aquari.degov.ai/degov.yml
      indexer: https://aquari.degov.ai/indexer/graphql

  - name: Virtuals DAO
    code: virtuals-dao
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://virtuals.degov.ai
      config: https://virtuals.degov.ai/degov.yml
      indexer: https://virtuals.degov.ai/indexer/graphql
