daos:
  - name: DeGov Development Test DAO
    code: degov-test-dao
    # xprofile: roasted
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://demo.degov.ai
      config: https://demo.degov.ai/degov.yml
      indexer: https://degov-indexer.vercel.app/graphql

  - name: RingDAO
    code: ring-dao
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://gov.ringdao.com
      config: https://gov.ringdao.com/degov.yml
      indexer: https://gov.ringdao.com/indexer/graphql

  - name: KtonDAO
    code: kton-dao
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://gov.ktondao.xyz
      config: https://gov.ktondao.xyz/degov.yml
      indexer: https://gov.ktondao.xyz/indexer/graphql

  - name: RingDAO Community Guild
    code: ringdao-guild
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://guild-gov.ringdao.com
      config: https://guild-gov.ringdao.com/degov.yml
      indexer: https://guild-gov.ringdao.com/indexer/graphql

  - name: Uniswap DAO
    code: uniswap-dao
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://uniswap.degov.ai
      config: https://uniswap.degov.ai/degov.yml
      indexer: https://uniswap.degov.ai/indexer/graphql

  - name: ENS DAO
    code: ens-dao
    xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    links:
      website: https://ens.degov.ai
      config: https://ens.degov.ai/degov.yml
      indexer: https://ens.degov.ai/indexer/graphql


