daos:

  ## Degov test dao
  - xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    extend: https://demo.degov.ai/degov.yml

  ## Ring DAO
  - xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    extend: https://gov.ringdao.com/degov.yml

  ## kton dao
  - xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    extend: https://gov.ktondao.xyz/degov.yml

  ## RingDAO Community Guild
  - xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    extend: https://guild-gov.ringdao.com/degov.yml

  ## ENS DAO
  - xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    extend: https://ens.degov.ai/degov.yml

  ## Aquari DAO
  - xprofile: official
    carry:
      - "#Governance"
      - "#DeFAI"
      - "#DAO"
    extend: https://aquari.degov.ai/degov.yml
