
daos:
  - name: DeGov Development Test DAO
    code: degov-test-dao
    # xprofile: roasted
    xprofile: official
    artifacts:
      - '#DeGov'
      - '@DeGovRoasted'
    links:
      website: https://demo.degov.ai
      config: https://demo.degov.ai/degov.yml
      indexer: https://degov-indexer.vercel.app/graphql

  # - name: Ring DAO
  #   code: ring-dao
  #   links:
  #     website: https://gov.ringdao.com
  #     config: https://gov.ringdao.com/degov.yml
  #     indexer: https://gov.ringdao.com/indexer/graphql

  # - name: Kton DAO
  #   code: kton-dao
  #   links:
  #     website: https://gov.ktondao.xyz
  #     config: https://gov.ktondao.xyz/degov.yml
  #     indexer: https://gov.ktondao.xyz/indexer/graphql

  # - name: RingDAO Community Guild
  #   code: ringdao-guild
  #   links:
  #     website: https://guild-gov.ringdao.com
  #     config: https://guild-gov.ringdao.com/degov.yml
  #     indexer: https://guild-gov.ringdao.com/indexer/graphql

