app:
  name: 'TK Token Wrap'
  logo: '/logo.svg'
  description: 'Wrap RING tokens to xRING and unwrap xRING back to RING tokens'
  chainId: 46
  wallet:
    walletConnectProjectId: '2719448e2ce94fdd269a3c8587123bcc'
  sourceToken:
    symbol: 'TK'
    decimals: 18
    address: '0x48C817eebE1fD79F946bd6b976EF579540517121'
    icon: '/example/token.svg'
  wrapToken:
    symbol: 'GTK'
    decimals: 18
    address: '0x0ef0827A9d5D329DFbaA14c7d5Aae364453A4D32'
    icon: '/example/token.svg'
  wrapContractAddress: '0x0ef0827A9d5D329DFbaA14c7d5Aae364453A4D32'
