name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  release-docker-image:
    name: Release docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - ai-agent
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - uses: benjlevesque/short-sha@v3.0
      - uses: olegtarasov/get-tag@v2.1.4

      - name: Publish docker image hash
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.package }}
          file: ${{ matrix.package }}/Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ matrix.package }}:sha-${{ env.SHA }}

      - name: Publish docker image tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          IMAGE_TAG_HASH=${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ matrix.package }}
          docker tag ${IMAGE_TAG_HASH}:sha-${{ env.SHA }} ${IMAGE_TAG_HASH}:${{ env.GIT_TAG_NAME }}
          docker push ${IMAGE_TAG_HASH}:${{ env.GIT_TAG_NAME }}
